-- =============================================================================
-- V12__sequences_dotnet.sql
-- TASK-25 (DB-01). Cria as 20 sequences do domínio .NET que o EF Core declara
-- via HasDefaultValueSql("SEQ_x.NEXTVAL") e que o Flyway — única autoridade de
-- DDL (CLAUDE.md / D-10) — nunca criou. Sem elas, qualquer base que não tenha
-- sido bootstrapada pelo DevOps-Cloud/db/init/01_schema.sql quebra com
-- ORA-02289 (sequence does not exist).
--
-- Caminho A (decisão travada): alinha-se o Flyway ao .NET, não o contrário.
-- Zero mudança de código no .NET — nenhuma *Configuration.cs é tocada.
-- Isso também restabelece a convenção documentada em CLAUDE.md:
--   "PKs .NET: Oracle sequences (DEFAULT SEQ_xxx.NEXTVAL)".
--
-- Além de criar as sequences, converte a PK das 20 tabelas .NET-owned de
-- GENERATED BY DEFAULT AS IDENTITY (V1/V9) para DEFAULT SEQ_x.NEXTVAL. A
-- conversão é obrigatória, não cosmética: manter os dois geradores ativos na
-- mesma coluna (identity contando a partir de 1 + sequence a partir de 100)
-- criaria colisão de PK assim que o contador do identity alcançasse a sequence.
--
-- Mapa completo das 25 tabelas (quais convertem, quais não, e por quê):
--   docs/V12-pk-strategy-map.md
--
-- Fora do escopo (documentado no mapa como risco/dívida):
--   · AGENDAMENTO  — shared-write; EF não declara sequence, JPA usa
--                    SEQ_AGENDAMENTO. Estratégia dupla pré-existente à V12.
--   · CONTA_TUTOR / CONSENTIMENTO / IDEMPOTENCY_KEY — Java owns, JPA usa
--                    GenerationType.IDENTITY. Suas sequences da V1 estão órfãs.
--   · TUTOR_PET    — PK composta, sem coluna gerada.
--
-- Sintaxe: Oracle 12c+ (ALTER TABLE ... MODIFY (col DROP IDENTITY)).
-- START WITH 100 — mesma convenção das 4 sequences da V1; fica acima do maior
-- ID dos seeds de dev (que vão até 5) e das linhas existentes em prod.
--
-- Por que este arquivo mora em db/migration-oracle/ e não em db/migration/:
-- o H2 (perfil dev) rejeita `MODIFY (col DROP IDENTITY)` com
-- "Unknown data type: DROP" — a sintaxe equivalente lá é
-- `ALTER COLUMN col DROP IDENTITY`. Mesmo motivo de V2/V3/V5. A variante
-- portável está em db/migration-h2/V12__sequences_dotnet.sql. As duas
-- localizações NÃO podem conter a mesma versão ao mesmo tempo (dev carrega
-- migration + migration-h2; prod carrega migration + migration-oracle).
-- =============================================================================

-- ─── 1. Sequences das 9 tabelas .NET-owned nascidas na V1 ────────────────────
CREATE SEQUENCE SEQ_CLINICA        START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ESPECIE        START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TIPO_EVENTO    START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RACA           START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_VETERINARIO    START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TUTOR          START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PET            START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_INVITE_TUTOR   START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_EVENTO_CLINICO START WITH 100 INCREMENT BY 1;

-- ─── 2. Sequences das 11 tabelas .NET-owned nascidas na V9 ───────────────────
-- ATENÇÃO: SEQ_LEITURA_TEMP e SEQ_ALERTA_TEMP são abreviadas — os nomes vêm
-- literalmente de LeituraTemperaturaConfiguration.cs / AlertaTemperaturaConfiguration.cs.
-- Não "corrigir" para SEQ_LEITURA_TEMPERATURA / SEQ_ALERTA_TEMPERATURA.
CREATE SEQUENCE SEQ_MEDICAMENTO    START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_NOTIFICACAO    START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DISPOSITIVO_IOT START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_LEITURA_TEMP   START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ALERTA_TEMP    START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TRIAGEM_LUNA   START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_EXAME          START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_VACINA         START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PRESCRICAO     START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DOCUMENTO      START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CONSULTA       START WITH 100 INCREMENT BY 1;

-- ─── 3. Conversão IDENTITY → DEFAULT SEQ_x.NEXTVAL (tabelas da V1) ───────────
-- DROP IDENTITY remove o gerador implícito e a sequence-sombra do Oracle; a
-- coluna volta a ser NUMBER(10) comum e passa a receber o default explícito.
-- A PK continua garantindo NOT NULL.
ALTER TABLE CLINICA        MODIFY (ID_CLINICA      DROP IDENTITY);
ALTER TABLE CLINICA        MODIFY (ID_CLINICA      DEFAULT SEQ_CLINICA.NEXTVAL);

ALTER TABLE ESPECIE        MODIFY (ID_ESPECIE      DROP IDENTITY);
ALTER TABLE ESPECIE        MODIFY (ID_ESPECIE      DEFAULT SEQ_ESPECIE.NEXTVAL);

ALTER TABLE TIPO_EVENTO    MODIFY (ID_TIPO_EVENTO  DROP IDENTITY);
ALTER TABLE TIPO_EVENTO    MODIFY (ID_TIPO_EVENTO  DEFAULT SEQ_TIPO_EVENTO.NEXTVAL);

ALTER TABLE RACA           MODIFY (ID_RACA         DROP IDENTITY);
ALTER TABLE RACA           MODIFY (ID_RACA         DEFAULT SEQ_RACA.NEXTVAL);

ALTER TABLE VETERINARIO    MODIFY (ID_VETERINARIO  DROP IDENTITY);
ALTER TABLE VETERINARIO    MODIFY (ID_VETERINARIO  DEFAULT SEQ_VETERINARIO.NEXTVAL);

ALTER TABLE TUTOR          MODIFY (ID_TUTOR        DROP IDENTITY);
ALTER TABLE TUTOR          MODIFY (ID_TUTOR        DEFAULT SEQ_TUTOR.NEXTVAL);

ALTER TABLE PET            MODIFY (ID_PET          DROP IDENTITY);
ALTER TABLE PET            MODIFY (ID_PET          DEFAULT SEQ_PET.NEXTVAL);

ALTER TABLE INVITE_TUTOR   MODIFY (ID_INVITE       DROP IDENTITY);
ALTER TABLE INVITE_TUTOR   MODIFY (ID_INVITE       DEFAULT SEQ_INVITE_TUTOR.NEXTVAL);

ALTER TABLE EVENTO_CLINICO MODIFY (ID_EVENTO       DROP IDENTITY);
ALTER TABLE EVENTO_CLINICO MODIFY (ID_EVENTO       DEFAULT SEQ_EVENTO_CLINICO.NEXTVAL);

-- ─── 4. Conversão IDENTITY → DEFAULT SEQ_x.NEXTVAL (tabelas da V9) ───────────
-- A V9 documentava a escolha do IDENTITY como "funcionalmente equivalente ao
-- SEQ_x.NEXTVAL que o EF espera". É equivalente no INSERT, mas não resolve a
-- ausência do objeto SEQUENCE — que é exatamente o ORA-02289 desta task.
ALTER TABLE MEDICAMENTO         MODIFY (ID_MEDICAMENTO DROP IDENTITY);
ALTER TABLE MEDICAMENTO         MODIFY (ID_MEDICAMENTO DEFAULT SEQ_MEDICAMENTO.NEXTVAL);

ALTER TABLE NOTIFICACAO         MODIFY (ID_NOTIFICACAO DROP IDENTITY);
ALTER TABLE NOTIFICACAO         MODIFY (ID_NOTIFICACAO DEFAULT SEQ_NOTIFICACAO.NEXTVAL);

ALTER TABLE DISPOSITIVO_IOT     MODIFY (ID_DISPOSITIVO DROP IDENTITY);
ALTER TABLE DISPOSITIVO_IOT     MODIFY (ID_DISPOSITIVO DEFAULT SEQ_DISPOSITIVO_IOT.NEXTVAL);

ALTER TABLE LEITURA_TEMPERATURA MODIFY (ID_LEITURA     DROP IDENTITY);
ALTER TABLE LEITURA_TEMPERATURA MODIFY (ID_LEITURA     DEFAULT SEQ_LEITURA_TEMP.NEXTVAL);

ALTER TABLE ALERTA_TEMPERATURA  MODIFY (ID_ALERTA      DROP IDENTITY);
ALTER TABLE ALERTA_TEMPERATURA  MODIFY (ID_ALERTA      DEFAULT SEQ_ALERTA_TEMP.NEXTVAL);

ALTER TABLE TRIAGEM_LUNA        MODIFY (ID_TRIAGEM     DROP IDENTITY);
ALTER TABLE TRIAGEM_LUNA        MODIFY (ID_TRIAGEM     DEFAULT SEQ_TRIAGEM_LUNA.NEXTVAL);

ALTER TABLE EXAME               MODIFY (ID_EXAME       DROP IDENTITY);
ALTER TABLE EXAME               MODIFY (ID_EXAME       DEFAULT SEQ_EXAME.NEXTVAL);

ALTER TABLE VACINA              MODIFY (ID_VACINA      DROP IDENTITY);
ALTER TABLE VACINA              MODIFY (ID_VACINA      DEFAULT SEQ_VACINA.NEXTVAL);

ALTER TABLE PRESCRICAO          MODIFY (ID_PRESCRICAO  DROP IDENTITY);
ALTER TABLE PRESCRICAO          MODIFY (ID_PRESCRICAO  DEFAULT SEQ_PRESCRICAO.NEXTVAL);

ALTER TABLE DOCUMENTO           MODIFY (ID_DOCUMENTO   DROP IDENTITY);
ALTER TABLE DOCUMENTO           MODIFY (ID_DOCUMENTO   DEFAULT SEQ_DOCUMENTO.NEXTVAL);

ALTER TABLE CONSULTA            MODIFY (ID_CONSULTA    DROP IDENTITY);
ALTER TABLE CONSULTA            MODIFY (ID_CONSULTA    DEFAULT SEQ_CONSULTA.NEXTVAL);
